# Generated by Django 6.0.3 on 2026-03-07 20:04

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id_price_history', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price_product', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_price_product', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id_product', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_product', models.CharField(max_length=200)),
                ('description_product', models.TextField()),
                ('price_product', models.DecimalField(decimal_places=2, max_digits=10)),
                ('initial_stock', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('current_stock', models.IntegerField()),
                ('expiration_date', models.DateField()),
                ('publication_date', models.DateTimeField(auto_now_add=True)),
                ('recovery_address', models.CharField(max_length=200)),
                ('recovery_time_limit', models.DateTimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
        ),
    ]
