# Generated by Django 6.0.3 on 2026-03-11 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_product',
            field=models.ImageField(blank=True, null=True, upload_to='product/'),
        ),
    ]
