# Generated by Django 6.0.3 on 2026-03-22 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_image_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description_product',
            field=models.TextField(blank=True, default=''),
        ),
    ]
