# Generated by Django 6.0.3 on 2026-03-23 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_description_product'),
        ('products', '0004_product_latitude_product_longitude_and_more'),
    ]

    operations = [
    ]
