--
-- PostgreSQL database dump
--

\restrict Cucze7GrlrfGogENzGAqM2INhoB3mbYZts6bbyqqpCTL9XXlcrVBtaslpUhMv7s

-- Dumped from database version 18.3
-- Dumped by pg_dump version 18.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: antigaspillageuser
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO antigaspillageuser;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: antigaspillageuser
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: antigaspillageuser
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO antigaspillageuser;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: antigaspillageuser
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: antigaspillageuser
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO antigaspillageuser;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: antigaspillageuser
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: badge_badge; Type: TABLE; Schema: public; Owner: antigaspillageuser
--

CREATE TABLE public.badge_badge (
    id_badge uuid NOT NULL,
    name_badge character varying(100) NOT NULL,
    picture_badge character varying(100) NOT NULL,
    obtaining_alone_badge integer NOT NULL,
    badge_type character varying(10) NOT NULL
);


ALTER TABLE public.badge_badge OWNER TO antigaspillageuser;

--
-- Name: category_category; Type: TABLE; Schema: public; Owner: antigaspillageuser
--

CREATE TABLE public.category_category (
    id_category uuid NOT NULL,
    name_category character varying(20) NOT NULL
);


ALTER TABLE public.category_category OWNER TO antigaspillageuser;

--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: antigaspillageuser
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id uuid NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO antigaspillageuser;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: antigaspillageuser
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: antigaspillageuser
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO antigaspillageuser;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: antigaspillageuser
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: antigaspillageuser
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO antigaspillageuser;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: antigaspillageuser
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: antigaspillageuser
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO antigaspillageuser;

--
-- Name: products_pricehistory; Type: TABLE; Schema: public; Owner: antigaspillageuser
--

CREATE TABLE public.products_pricehistory (
    id_price_history uuid NOT NULL,
    price_product numeric(10,2) NOT NULL,
    date_price_product timestamp with time zone NOT NULL,
    product_id uuid NOT NULL
);


ALTER TABLE public.products_pricehistory OWNER TO antigaspillageuser;

--
-- Name: products_product; Type: TABLE; Schema: public; Owner: antigaspillageuser
--

CREATE TABLE public.products_product (
    id_product uuid NOT NULL,
    name_product character varying(200) NOT NULL,
    description_product text NOT NULL,
    price_product numeric(10,2) NOT NULL,
    initial_stock integer NOT NULL,
    current_stock integer NOT NULL,
    expiration_date date NOT NULL,
    publication_date timestamp with time zone NOT NULL,
    recovery_address character varying(200) NOT NULL,
    recovery_time_limit timestamp with time zone NOT NULL,
    is_available boolean NOT NULL,
    category_id uuid NOT NULL,
    user_id uuid NOT NULL,
    image_product character varying(100),
    latitude numeric(9,6),
    longitude numeric(9,6)
);


ALTER TABLE public.products_product OWNER TO antigaspillageuser;

--
-- Name: reservations_reservation; Type: TABLE; Schema: public; Owner: antigaspillageuser
--

CREATE TABLE public.reservations_reservation (
    id_reservation uuid NOT NULL,
    quantity_reserved integer NOT NULL,
    estimated_recovery_time timestamp with time zone NOT NULL,
    date_reservation timestamp with time zone NOT NULL,
    status_reservation character varying(20) NOT NULL,
    product_id uuid NOT NULL,
    user_id uuid NOT NULL
);


ALTER TABLE public.reservations_reservation OWNER TO antigaspillageuser;

--
-- Name: reviews_review; Type: TABLE; Schema: public; Owner: antigaspillageuser
--

CREATE TABLE public.reviews_review (
    id_review uuid NOT NULL,
    rating_review numeric(2,1) NOT NULL,
    comment_review character varying(500) NOT NULL,
    date_review timestamp with time zone NOT NULL,
    product_id uuid NOT NULL,
    user_id uuid NOT NULL
);


ALTER TABLE public.reviews_review OWNER TO antigaspillageuser;

--
-- Name: token_blacklist_blacklistedtoken; Type: TABLE; Schema: public; Owner: antigaspillageuser
--

CREATE TABLE public.token_blacklist_blacklistedtoken (
    id bigint NOT NULL,
    blacklisted_at timestamp with time zone NOT NULL,
    token_id bigint NOT NULL
);


ALTER TABLE public.token_blacklist_blacklistedtoken OWNER TO antigaspillageuser;

--
-- Name: token_blacklist_blacklistedtoken_id_seq; Type: SEQUENCE; Schema: public; Owner: antigaspillageuser
--

ALTER TABLE public.token_blacklist_blacklistedtoken ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.token_blacklist_blacklistedtoken_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: token_blacklist_outstandingtoken; Type: TABLE; Schema: public; Owner: antigaspillageuser
--

CREATE TABLE public.token_blacklist_outstandingtoken (
    id bigint NOT NULL,
    token text NOT NULL,
    created_at timestamp with time zone,
    expires_at timestamp with time zone NOT NULL,
    user_id uuid,
    jti character varying(255) CONSTRAINT token_blacklist_outstandingtoken_jti_hex_not_null NOT NULL
);


ALTER TABLE public.token_blacklist_outstandingtoken OWNER TO antigaspillageuser;

--
-- Name: token_blacklist_outstandingtoken_id_seq; Type: SEQUENCE; Schema: public; Owner: antigaspillageuser
--

ALTER TABLE public.token_blacklist_outstandingtoken ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.token_blacklist_outstandingtoken_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_user; Type: TABLE; Schema: public; Owner: antigaspillageuser
--

CREATE TABLE public.users_user (
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    id_user uuid NOT NULL,
    tel1_user character varying(20),
    tel2_user character varying(20),
    address_user character varying(50),
    profile_pic_user character varying(100),
    saved_in_90_days integer NOT NULL,
    total_product_saved integer NOT NULL
);


ALTER TABLE public.users_user OWNER TO antigaspillageuser;

--
-- Name: users_user_groups; Type: TABLE; Schema: public; Owner: antigaspillageuser
--

CREATE TABLE public.users_user_groups (
    id bigint NOT NULL,
    user_id uuid NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.users_user_groups OWNER TO antigaspillageuser;

--
-- Name: users_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: antigaspillageuser
--

ALTER TABLE public.users_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_user_user_permissions; Type: TABLE; Schema: public; Owner: antigaspillageuser
--

CREATE TABLE public.users_user_user_permissions (
    id bigint NOT NULL,
    user_id uuid NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.users_user_user_permissions OWNER TO antigaspillageuser;

--
-- Name: users_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: antigaspillageuser
--

ALTER TABLE public.users_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_userbadge; Type: TABLE; Schema: public; Owner: antigaspillageuser
--

CREATE TABLE public.users_userbadge (
    id bigint NOT NULL,
    badge_id uuid NOT NULL,
    user_id uuid NOT NULL
);


ALTER TABLE public.users_userbadge OWNER TO antigaspillageuser;

--
-- Name: users_userbadge_id_seq; Type: SEQUENCE; Schema: public; Owner: antigaspillageuser
--

ALTER TABLE public.users_userbadge ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_userbadge_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: antigaspillageuser
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: antigaspillageuser
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: antigaspillageuser
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: antigaspillageuser
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: antigaspillageuser
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: antigaspillageuser
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: badge_badge badge_badge_badge_type_key; Type: CONSTRAINT; Schema: public; Owner: antigaspillageuser
--

ALTER TABLE ONLY public.badge_badge
    ADD CONSTRAINT badge_badge_badge_type_key UNIQUE (badge_type);


--
-- Name: badge_badge badge_badge_pkey; Type: CONSTRAINT; Schema: public; Owner: antigaspillageuser
--

ALTER TABLE ONLY public.badge_badge
    ADD CONSTRAINT badge_badge_pkey PRIMARY KEY (id_badge);


--
-- Name: category_category category_category_pkey; Type: CONSTRAINT; Schema: public; Owner: antigaspillageuser
--

ALTER TABLE ONLY public.category_category
    ADD CONSTRAINT category_category_pkey PRIMARY KEY (id_category);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: antigaspillageuser
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: antigaspillageuser
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: antigaspillageuser
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: antigaspillageuser
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: antigaspillageuser
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: products_pricehistory products_pricehistory_pkey; Type: CONSTRAINT; Schema: public; Owner: antigaspillageuser
--

ALTER TABLE ONLY public.products_pricehistory
    ADD CONSTRAINT products_pricehistory_pkey PRIMARY KEY (id_price_history);


--
-- Name: products_product products_product_pkey; Type: CONSTRAINT; Schema: public; Owner: antigaspillageuser
--

ALTER TABLE ONLY public.products_product
    ADD CONSTRAINT products_product_pkey PRIMARY KEY (id_product);


--
-- Name: reservations_reservation reservations_reservation_pkey; Type: CONSTRAINT; Schema: public; Owner: antigaspillageuser
--

ALTER TABLE ONLY public.reservations_reservation
    ADD CONSTRAINT reservations_reservation_pkey PRIMARY KEY (id_reservation);


--
-- Name: reviews_review reviews_review_pkey; Type: CONSTRAINT; Schema: public; Owner: antigaspillageuser
--

ALTER TABLE ONLY public.reviews_review
    ADD CONSTRAINT reviews_review_pkey PRIMARY KEY (id_review);


--
-- Name: token_blacklist_blacklistedtoken token_blacklist_blacklistedtoken_pkey; Type: CONSTRAINT; Schema: public; Owner: antigaspillageuser
--

ALTER TABLE ONLY public.token_blacklist_blacklistedtoken
    ADD CONSTRAINT token_blacklist_blacklistedtoken_pkey PRIMARY KEY (id);


--
-- Name: token_blacklist_blacklistedtoken token_blacklist_blacklistedtoken_token_id_key; Type: CONSTRAINT; Schema: public; Owner: antigaspillageuser
--

ALTER TABLE ONLY public.token_blacklist_blacklistedtoken
    ADD CONSTRAINT token_blacklist_blacklistedtoken_token_id_key UNIQUE (token_id);


--
-- Name: token_blacklist_outstandingtoken token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_uniq; Type: CONSTRAINT; Schema: public; Owner: antigaspillageuser
--

ALTER TABLE ONLY public.token_blacklist_outstandingtoken
    ADD CONSTRAINT token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_uniq UNIQUE (jti);


--
-- Name: token_blacklist_outstandingtoken token_blacklist_outstandingtoken_pkey; Type: CONSTRAINT; Schema: public; Owner: antigaspillageuser
--

ALTER TABLE ONLY public.token_blacklist_outstandingtoken
    ADD CONSTRAINT token_blacklist_outstandingtoken_pkey PRIMARY KEY (id);


--
-- Name: users_user_groups users_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: antigaspillageuser
--

ALTER TABLE ONLY public.users_user_groups
    ADD CONSTRAINT users_user_groups_pkey PRIMARY KEY (id);


--
-- Name: users_user_groups users_user_groups_user_id_group_id_b88eab82_uniq; Type: CONSTRAINT; Schema: public; Owner: antigaspillageuser
--

ALTER TABLE ONLY public.users_user_groups
    ADD CONSTRAINT users_user_groups_user_id_group_id_b88eab82_uniq UNIQUE (user_id, group_id);


--
-- Name: users_user users_user_pkey; Type: CONSTRAINT; Schema: public; Owner: antigaspillageuser
--

ALTER TABLE ONLY public.users_user
    ADD CONSTRAINT users_user_pkey PRIMARY KEY (id_user);


--
-- Name: users_user_user_permissions users_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: antigaspillageuser
--

ALTER TABLE ONLY public.users_user_user_permissions
    ADD CONSTRAINT users_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: users_user_user_permissions users_user_user_permissions_user_id_permission_id_43338c45_uniq; Type: CONSTRAINT; Schema: public; Owner: antigaspillageuser
--

ALTER TABLE ONLY public.users_user_user_permissions
    ADD CONSTRAINT users_user_user_permissions_user_id_permission_id_43338c45_uniq UNIQUE (user_id, permission_id);


--
-- Name: users_user users_user_username_key; Type: CONSTRAINT; Schema: public; Owner: antigaspillageuser
--

ALTER TABLE ONLY public.users_user
    ADD CONSTRAINT users_user_username_key UNIQUE (username);


--
-- Name: users_userbadge users_userbadge_pkey; Type: CONSTRAINT; Schema: public; Owner: antigaspillageuser
--

ALTER TABLE ONLY public.users_userbadge
    ADD CONSTRAINT users_userbadge_pkey PRIMARY KEY (id);


--
-- Name: users_userbadge users_userbadge_user_id_badge_id_c72c4099_uniq; Type: CONSTRAINT; Schema: public; Owner: antigaspillageuser
--

ALTER TABLE ONLY public.users_userbadge
    ADD CONSTRAINT users_userbadge_user_id_badge_id_c72c4099_uniq UNIQUE (user_id, badge_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: antigaspillageuser
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: antigaspillageuser
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: antigaspillageuser
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: antigaspillageuser
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: badge_badge_badge_type_fd030e88_like; Type: INDEX; Schema: public; Owner: antigaspillageuser
--

CREATE INDEX badge_badge_badge_type_fd030e88_like ON public.badge_badge USING btree (badge_type varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: antigaspillageuser
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: antigaspillageuser
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: antigaspillageuser
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: antigaspillageuser
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: products_pricehistory_product_id_1fc0e3fe; Type: INDEX; Schema: public; Owner: antigaspillageuser
--

CREATE INDEX products_pricehistory_product_id_1fc0e3fe ON public.products_pricehistory USING btree (product_id);


--
-- Name: products_product_category_id_9b594869; Type: INDEX; Schema: public; Owner: antigaspillageuser
--

CREATE INDEX products_product_category_id_9b594869 ON public.products_product USING btree (category_id);


--
-- Name: products_product_user_id_e04f062e; Type: INDEX; Schema: public; Owner: antigaspillageuser
--

CREATE INDEX products_product_user_id_e04f062e ON public.products_product USING btree (user_id);


--
-- Name: reservations_reservation_product_id_31ac5c20; Type: INDEX; Schema: public; Owner: antigaspillageuser
--

CREATE INDEX reservations_reservation_product_id_31ac5c20 ON public.reservations_reservation USING btree (product_id);


--
-- Name: reservations_reservation_user_id_6ed5b1c9; Type: INDEX; Schema: public; Owner: antigaspillageuser
--

CREATE INDEX reservations_reservation_user_id_6ed5b1c9 ON public.reservations_reservation USING btree (user_id);


--
-- Name: reviews_review_product_id_ce2fa4c6; Type: INDEX; Schema: public; Owner: antigaspillageuser
--

CREATE INDEX reviews_review_product_id_ce2fa4c6 ON public.reviews_review USING btree (product_id);


--
-- Name: reviews_review_user_id_875caff2; Type: INDEX; Schema: public; Owner: antigaspillageuser
--

CREATE INDEX reviews_review_user_id_875caff2 ON public.reviews_review USING btree (user_id);


--
-- Name: token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_like; Type: INDEX; Schema: public; Owner: antigaspillageuser
--

CREATE INDEX token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_like ON public.token_blacklist_outstandingtoken USING btree (jti varchar_pattern_ops);


--
-- Name: token_blacklist_outstandingtoken_user_id_83bc629a; Type: INDEX; Schema: public; Owner: antigaspillageuser
--

CREATE INDEX token_blacklist_outstandingtoken_user_id_83bc629a ON public.token_blacklist_outstandingtoken USING btree (user_id);


--
-- Name: users_user_groups_group_id_9afc8d0e; Type: INDEX; Schema: public; Owner: antigaspillageuser
--

CREATE INDEX users_user_groups_group_id_9afc8d0e ON public.users_user_groups USING btree (group_id);


--
-- Name: users_user_groups_user_id_5f6f5a90; Type: INDEX; Schema: public; Owner: antigaspillageuser
--

CREATE INDEX users_user_groups_user_id_5f6f5a90 ON public.users_user_groups USING btree (user_id);


--
-- Name: users_user_user_permissions_permission_id_0b93982e; Type: INDEX; Schema: public; Owner: antigaspillageuser
--

CREATE INDEX users_user_user_permissions_permission_id_0b93982e ON public.users_user_user_permissions USING btree (permission_id);


--
-- Name: users_user_user_permissions_user_id_20aca447; Type: INDEX; Schema: public; Owner: antigaspillageuser
--

CREATE INDEX users_user_user_permissions_user_id_20aca447 ON public.users_user_user_permissions USING btree (user_id);


--
-- Name: users_user_username_06e46fe6_like; Type: INDEX; Schema: public; Owner: antigaspillageuser
--

CREATE INDEX users_user_username_06e46fe6_like ON public.users_user USING btree (username varchar_pattern_ops);


--
-- Name: users_userbadge_badge_id_663925dd; Type: INDEX; Schema: public; Owner: antigaspillageuser
--

CREATE INDEX users_userbadge_badge_id_663925dd ON public.users_userbadge USING btree (badge_id);


--
-- Name: users_userbadge_user_id_2b82720a; Type: INDEX; Schema: public; Owner: antigaspillageuser
--

CREATE INDEX users_userbadge_user_id_2b82720a ON public.users_userbadge USING btree (user_id);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: antigaspillageuser
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: antigaspillageuser
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: antigaspillageuser
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: antigaspillageuser
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_users_user_id_user; Type: FK CONSTRAINT; Schema: public; Owner: antigaspillageuser
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_users_user_id_user FOREIGN KEY (user_id) REFERENCES public.users_user(id_user) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: products_pricehistory products_pricehistor_product_id_1fc0e3fe_fk_products_; Type: FK CONSTRAINT; Schema: public; Owner: antigaspillageuser
--

ALTER TABLE ONLY public.products_pricehistory
    ADD CONSTRAINT products_pricehistor_product_id_1fc0e3fe_fk_products_ FOREIGN KEY (product_id) REFERENCES public.products_product(id_product) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: products_product products_product_category_id_9b594869_fk_category_; Type: FK CONSTRAINT; Schema: public; Owner: antigaspillageuser
--

ALTER TABLE ONLY public.products_product
    ADD CONSTRAINT products_product_category_id_9b594869_fk_category_ FOREIGN KEY (category_id) REFERENCES public.category_category(id_category) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: products_product products_product_user_id_e04f062e_fk_users_user_id_user; Type: FK CONSTRAINT; Schema: public; Owner: antigaspillageuser
--

ALTER TABLE ONLY public.products_product
    ADD CONSTRAINT products_product_user_id_e04f062e_fk_users_user_id_user FOREIGN KEY (user_id) REFERENCES public.users_user(id_user) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: reservations_reservation reservations_reserva_product_id_31ac5c20_fk_products_; Type: FK CONSTRAINT; Schema: public; Owner: antigaspillageuser
--

ALTER TABLE ONLY public.reservations_reservation
    ADD CONSTRAINT reservations_reserva_product_id_31ac5c20_fk_products_ FOREIGN KEY (product_id) REFERENCES public.products_product(id_product) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: reservations_reservation reservations_reservation_user_id_6ed5b1c9_fk_users_user_id_user; Type: FK CONSTRAINT; Schema: public; Owner: antigaspillageuser
--

ALTER TABLE ONLY public.reservations_reservation
    ADD CONSTRAINT reservations_reservation_user_id_6ed5b1c9_fk_users_user_id_user FOREIGN KEY (user_id) REFERENCES public.users_user(id_user) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: reviews_review reviews_review_product_id_ce2fa4c6_fk_products_; Type: FK CONSTRAINT; Schema: public; Owner: antigaspillageuser
--

ALTER TABLE ONLY public.reviews_review
    ADD CONSTRAINT reviews_review_product_id_ce2fa4c6_fk_products_ FOREIGN KEY (product_id) REFERENCES public.products_product(id_product) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: reviews_review reviews_review_user_id_875caff2_fk_users_user_id_user; Type: FK CONSTRAINT; Schema: public; Owner: antigaspillageuser
--

ALTER TABLE ONLY public.reviews_review
    ADD CONSTRAINT reviews_review_user_id_875caff2_fk_users_user_id_user FOREIGN KEY (user_id) REFERENCES public.users_user(id_user) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: token_blacklist_blacklistedtoken token_blacklist_blacklistedtoken_token_id_3cc7fe56_fk; Type: FK CONSTRAINT; Schema: public; Owner: antigaspillageuser
--

ALTER TABLE ONLY public.token_blacklist_blacklistedtoken
    ADD CONSTRAINT token_blacklist_blacklistedtoken_token_id_3cc7fe56_fk FOREIGN KEY (token_id) REFERENCES public.token_blacklist_outstandingtoken(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: token_blacklist_outstandingtoken token_blacklist_outs_user_id_83bc629a_fk_users_use; Type: FK CONSTRAINT; Schema: public; Owner: antigaspillageuser
--

ALTER TABLE ONLY public.token_blacklist_outstandingtoken
    ADD CONSTRAINT token_blacklist_outs_user_id_83bc629a_fk_users_use FOREIGN KEY (user_id) REFERENCES public.users_user(id_user) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_groups users_user_groups_group_id_9afc8d0e_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: antigaspillageuser
--

ALTER TABLE ONLY public.users_user_groups
    ADD CONSTRAINT users_user_groups_group_id_9afc8d0e_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_groups users_user_groups_user_id_5f6f5a90_fk_users_user_id_user; Type: FK CONSTRAINT; Schema: public; Owner: antigaspillageuser
--

ALTER TABLE ONLY public.users_user_groups
    ADD CONSTRAINT users_user_groups_user_id_5f6f5a90_fk_users_user_id_user FOREIGN KEY (user_id) REFERENCES public.users_user(id_user) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_user_permissions users_user_user_perm_permission_id_0b93982e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: antigaspillageuser
--

ALTER TABLE ONLY public.users_user_user_permissions
    ADD CONSTRAINT users_user_user_perm_permission_id_0b93982e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_user_permissions users_user_user_perm_user_id_20aca447_fk_users_use; Type: FK CONSTRAINT; Schema: public; Owner: antigaspillageuser
--

ALTER TABLE ONLY public.users_user_user_permissions
    ADD CONSTRAINT users_user_user_perm_user_id_20aca447_fk_users_use FOREIGN KEY (user_id) REFERENCES public.users_user(id_user) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_userbadge users_userbadge_badge_id_663925dd_fk_badge_badge_id_badge; Type: FK CONSTRAINT; Schema: public; Owner: antigaspillageuser
--

ALTER TABLE ONLY public.users_userbadge
    ADD CONSTRAINT users_userbadge_badge_id_663925dd_fk_badge_badge_id_badge FOREIGN KEY (badge_id) REFERENCES public.badge_badge(id_badge) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_userbadge users_userbadge_user_id_2b82720a_fk_users_user_id_user; Type: FK CONSTRAINT; Schema: public; Owner: antigaspillageuser
--

ALTER TABLE ONLY public.users_userbadge
    ADD CONSTRAINT users_userbadge_user_id_2b82720a_fk_users_user_id_user FOREIGN KEY (user_id) REFERENCES public.users_user(id_user) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: pg_database_owner
--

GRANT ALL ON SCHEMA public TO antigaspillageuser;


--
-- PostgreSQL database dump complete
--

\unrestrict Cucze7GrlrfGogENzGAqM2INhoB3mbYZts6bbyqqpCTL9XXlcrVBtaslpUhMv7s

