# Generated by Django 6.0.3 on 2026-03-07 20:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id_badge', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_badge', models.CharField(max_length=100)),
                ('picture_badge', models.ImageField(upload_to='products/')),
                ('obtaining_alone_badge', models.IntegerField()),
            ],
        ),
    ]
