# Generated by Django 6.0.3 on 2026-03-22 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='badge_type',
            field=models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold')], default='bronze', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='badge',
            name='obtaining_alone_badge',
            field=models.IntegerField(help_text='Nombre de produits sauvés requis'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='picture_badge',
            field=models.ImageField(upload_to='badges/'),
        ),
    ]
