# Generated by Django 6.0.3 on 2026-03-07 20:04

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id_reservation', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_reserved', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('estimated_recovery_time', models.DateTimeField()),
                ('date_reservation', models.DateTimeField(auto_now_add=True)),
                ('status_reservation', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('collected', 'Collected')], default='pending', max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
